# Generated by Django 3.2.7 on 2021-09-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visstability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edges',
            name='id_gr',
            field=models.CharField(default='ed_1', help_text='id ребра', max_length=10, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodes',
            name='layer',
            field=models.CharField(choices=[('it', 'ИТ-ресурс'), ('bs', 'Бизнес-система'), ('bu', 'Бизнес-услуга'), ('br', 'Бизнес-решение'), ('bp', 'Бизнес-процесс'), ('ot', 'Прочее')], help_text='Бизнес-слой', max_length=4, verbose_name='layer'),
        ),
    ]
