# Generated by Django 3.2.7 on 2021-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visstability', '0002_auto_20210917_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='costdown',
            field=models.FloatField(default=0, help_text='Стоимость простоя', verbose_name='costdown'),
            preserve_default=False,
        ),
    ]
