# Generated by Django 3.2.7 on 2021-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visstability', '0003_nodes_costdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='type_gr',
            field=models.CharField(choices=[('metric', 'метрика'), ('or', 'И'), ('and', 'ИЛИ'), ('true', 'единица'), ('service', 'сервис')], help_text='Тип вершины графа', max_length=10, verbose_name='type'),
        ),
    ]
